name: Publish
on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Checkout submodules
       run: git submodule update --init --recursive
     - name: Get Hugo
       uses: peaceiris/actions-hugo@v3
       with:
         hugo-version: '0.142.0'
         extended: true
     - name: Build Site
       run: hugo --minify
     - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       env:
         ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         EXTERNAL_REPOSITORY: 'kumpelblase2/kumpelblase2.github.io'
         PUBLISH_BRANCH: master
         PUBLISH_DIR: ./public
